apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-breaker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-breaker-server
  template:
    metadata:
      labels:
        app: code-breaker-server
    spec:
      containers:
      - name: server
        image: code-breaker-game
        command: ["./game-app", "-mode=mserver", "-players=2", "-timeout=15", "-addr=0.0.0.0:8080"]
        ports:
        - containerPort: 8080
