// Code generated by MockGen. DO NOT EDIT.
// Source: game_logic.go

// Package game is a generated GoMock package.
package game

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCodeGenerator is a mock of CodeGenerator interface.
type MockCodeGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockCodeGeneratorMockRecorder
}

// MockCodeGeneratorMockRecorder is the mock recorder for MockCodeGenerator.
type MockCodeGeneratorMockRecorder struct {
	mock *MockCodeGenerator
}

// NewMockCodeGenerator creates a new mock instance.
func NewMockCodeGenerator(ctrl *gomock.Controller) *MockCodeGenerator {
	mock := &MockCodeGenerator{ctrl: ctrl}
	mock.recorder = &MockCodeGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeGenerator) EXPECT() *MockCodeGeneratorMockRecorder {
	return m.recorder
}

// GenerateSecretCode mocks base method.
func (m *MockCodeGenerator) GenerateSecretCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecretCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// GenerateSecretCode indicates an expected call of GenerateSecretCode.
func (mr *MockCodeGeneratorMockRecorder) GenerateSecretCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecretCode", reflect.TypeOf((*MockCodeGenerator)(nil).GenerateSecretCode))
}
